networks:
    guedesapp:
        driver: 'bridge'
        ipam:
            config:
                - subnet: 172.35.122.0/24

services:

    php-apache:
        build: ../
        env_file:
            - path: ../.env
        ports:
            - 80:80
        volumes:
            - ../:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "dev.backend.com:172.32.122.22"
        networks:
            - guedesapp

    mongodb:
        image: mongo:8
        ports:
            - "27017:27017"
        volumes:
            - ./guedesappdb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: guedesapp_user
            MONGO_INITDB_ROOT_PASSWORD: guedesapp_pass
            MONGO_INITDB_DATABASE: guedesapp
        networks:
            - guedesapp
volumes:
    guedesappdb: