controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
kernel:
    resource: App\Kernel
    type: attribute

packages_user_bundle.routes:
    resource: '@PackagesUserBundle/config/routes.yaml'